---
- name: Create Ec2 instance for web
  gather_facts: false
  hosts: localhost
  connection: local
  roles:
    - role: create_webnode

- name: Create Ec2 instance for app node
  gather_facts: false
  hosts: localhost
  connection: local
  roles:
   - role: create_appnode

- name: Configure web node
  gather_facts: false
  connection: ssh
  become: yes
  hosts: ec2-instances
  roles:
    - role: configure_webnode


- name: Configure appnode
  gather_facts: false
  connection: ssh
  become: yes
  hosts: app-instances
  roles:
    - role: configure_appnode
